home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
   
]

simulation/urls.py
from django.urls import path

from . import views

app_name = 'simulation'

urlpatterns = [
    path('', views.index, name='simulation'),
    path('score/', views.score, name='simulation-score'),
    path('survey/', views.survey, name='simulation-survey')
]

teka/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('otentikasi.urls')),
    path('simulation/', include('simulation.urls')),
    path('tips/', include('fitur.urls')),
    path('maps/', include('maps.urls')),
    path('feedback/', include('feedback.urls')),
]

simulation/models.py
from django.db import models
# from django.conf import settings 

# Create your models here.

class ObedienceSurveyResponse(models.Model):
    # associated_survey = models.OneToOneField(OPForm, on_delete=models.CASCADE, primary_key=True, default=get_opform)
    mask_obedience = models.IntegerField(default=50)
    PD_obedience = models.IntegerField(default=50)
    sntz_obedience = models.IntegerField(default=50)
    mask_type = models.CharField(max_length=1000, default='3-ply cloth mask')
    mask_behavior = models.CharField(max_length=1000, default='(No habit selected)')
    PD_experience = models.CharField(max_length=1000, default='I have tried distancing myself from strangers but I don\'t think it was 2 meters (6 ft 6 in) away or more')
    PD_area_space = models.CharField(max_length=1000, default='Uncrowded open area')
    sntz_wash_hand = models.CharField(max_length=1000, default='Yes, I wash my hands regularly')
    sntz_soap_type = models.CharField(max_length=1000, default='Bar soap')
    sntz_wash_time = models.CharField(max_length=1000, default='20 seconds') #fixed string
    sntz_occasions = models.CharField(max_length=1000, default='(No occasion selected)')
    sntz_hsanitizer = models.CharField(max_length=1000, default='Yes, I sanitize my hands when I don\'t have a proper access to wash them') 
    sntz_alcohol_percentage = models.CharField(max_length=1000, default='70%') #fixed string
    sntz_disinfect = models.CharField(max_length=1000, default='Yes, I usually disinfect things I bring from outside')

def get_ob_overall(ob_type):
    ob_overall_sum_float = 0.0
    ob_percentage_list = ObedienceSurveyResponse.objects.all()
    ob_percentage_count = ob_percentage_list.count()

    if ob_type == 'MASK' :
        for obp in ob_percentage_list:
            ob_overall_sum_float += obp.mask_obedience
    
    elif ob_type == 'PD':
        for obp in ob_percentage_list:
            ob_overall_sum_float += obp.PD_obedience

    elif ob_type == 'SNTZ' :
        for obp in ob_percentage_list:
            ob_overall_sum_float += obp.sntz_obedience

    try:
        ob_overall_mean = ob_overall_sum_float / ob_percentage_count

    except ZeroDivisionError:
        ob_overall_mean = 0

    return str('%.1f' %  ob_overall_mean)

simulation/views.py
from django.core import serializers
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
import json

from math import floor, ceil

from .forms import *
from .models import ObedienceSurveyResponse, get_ob_overall 

def index(request):
    redirect_page = 'simul-index.html'        
    test_form = TestForm(request.POST)
    mask_overall = get_ob_overall('MASK')
    pd_overall = get_ob_overall('PD')
    sntz_overall = get_ob_overall('SNTZ')
        
    context = {
        'test_form':test_form, 
        'mask_percentage':mask_overall,
        'pd_percentage':pd_overall,
        'sanitize_percentage':sntz_overall,
        }
    return render(request, template_name=redirect_page, context=context)

@login_required(login_url="login")
def survey(request):
    mask_form = MaskForm()
    pd_form = PDForm()
    sanitize_form = SanitizeForm()
    
    context = {
        'mask_form': mask_form, 
        'pd_form':pd_form, 
        'sanitize_form':sanitize_form,
    }
    return render(request, "simul-survey.html", context=context)

@login_required(login_url="login")
def score(request):
    mask_form = MaskForm()
    pd_form = PDForm()
    sanitize_form = SanitizeForm()

    if request.method == 'POST':
        if 'sanitize_wash_time' in request.POST :
            mask_form = MaskForm(request.POST)
            pd_form = PDForm(request.POST)
            sanitize_form = SanitizeForm(request.POST)
            if mask_form.is_valid() and pd_form.is_valid() and sanitize_form.is_valid():
                
                mask_type = mask_form.cleaned_data['mask_type_point']

                mask_behavior_list = request.POST.get('mask_behavior_point', [])
                if mask_behavior_list:  
                    mask_behavior_list = json.loads(mask_behavior_list)

                pd_exp = request.POST.get('pd_exp_point')

                pd_area_crowdedness = request.POST.get('pd_area_crowdedness_point')
                pd_area_openness = request.POST.get('pd_area_openness_point')

                sanitize_wash_hand_point = request.POST.get('sanitize_wash_hand_point')
                sanitize_soap_type_point = request.POST.get('sanitize_soap_type_point')
                sanitize_wash_time = int(request.POST.get('sanitize_wash_time'))

                sanitize_occasions_list = request.POST.get('sanitize_occasions_point', [])
                if sanitize_occasions_list:  
                    sanitize_occasions_list = json.loads(sanitize_occasions_list)

                sanitize_hsanitizer_point = request.POST.get('sanitize_hsanitizer_point')
                sanitize_alcohol_percentage = int(request.POST.get('sanitize_alcohol_percentage'))
                sanitize_disinfect_point = request.POST.get('sanitize_disinfect_point')

                mask_percentage = process_mask_percentage(mask_type, mask_behavior_list)
                pd_percentage = process_pd_percentage(pd_exp, pd_area_crowdedness, pd_area_openness)
                sanitize_percentage = process_sanitize_percentage(
                    sanitize_wash_hand_point,
                    sanitize_soap_type_point,
                    sanitize_wash_time, 
                    sanitize_hsanitizer_point,
                    sanitize_occasions_list,
                    sanitize_alcohol_percentage,
                    sanitize_disinfect_point
                    )

                mask_answer = [mask_type, get_list_as_p(mask_behavior_list, '(No habit selected)')]
                mask_response = zip(MASK_LABEL, mask_answer) #nanti ditulis manual di js :')

                pd_area_answer = str(pd_area_crowdedness) + ' ' + str(pd_area_openness).lower()
                pd_answer = [pd_exp, pd_area_answer]
                pd_response = zip(PD_LABEL, pd_answer) #nanti ditulis manual di js :')

                sntz_answer = [
                    sanitize_wash_hand_point, sanitize_soap_type_point, proccess_sanitize_wash_time(sanitize_wash_time),
                    get_list_as_p(sanitize_occasions_list, '(No occasion selected)'), sanitize_hsanitizer_point,
                    str(sanitize_alcohol_percentage) + '%', sanitize_disinfect_point,
                ]
                sntz_response = zip(SANITIZE_LABEL, sntz_answer) #nanti ditulis manual di js :')

                response_instance = ObedienceSurveyResponse.objects.create(
                    mask_obedience = mask_percentage,
                    PD_obedience = pd_percentage,
                    sntz_obedience = sanitize_percentage,
                    mask_type = mask_answer[0],
                    mask_behavior = mask_answer[1],
                    PD_experience = pd_answer[0],
                    PD_area_space = pd_answer[1],
                    sntz_wash_hand = sntz_answer[0],
                    sntz_soap_type = sntz_answer[1],
                    sntz_wash_time = sntz_answer[2],
                    sntz_occasions = sntz_answer[3],
                    sntz_hsanitizer = sntz_answer[4], 
                    sntz_alcohol_percentage = sntz_answer[5],
                    sntz_disinfect = sntz_answer[6]
                )
                
                response_instance.save()

                responses = ObedienceSurveyResponse.objects.all()
                responsesJSON = serializers.serialize('json', responses)
                return HttpResponse(responsesJSON, content_type='application/json')

        mask_form.errors.update(pd_form.errors)
        mask_form.errors.update(sanitize_form.errors)
        main_response = mask_form.errors.as_json()
        response = JsonResponse(main_response, safe=False)
        response.status_code = 403 # To announce that the user isn't allowed to publish
        return response

    #GET
    responses = ObedienceSurveyResponse.objects.all()
    responsesJSON = serializers.serialize('json', responses)
    return HttpResponse(responsesJSON, content_type='application/json')

def get_list_as_p(source_list, null_message):
    last_index = len(source_list) - 1
    if len(source_list) != 0:
        result_p = ''
        for i in range(last_index):
            result_p += '{}. {}<br>'.format(i+1, str(source_list[i]))
        result_p += '{}. {}'.format(last_index+1, str(source_list[last_index]))
        return result_p
    
    else: 
        return null_message

def process_wash_time_point(wash_time):
    wash_time = int(wash_time)
    if wash_time >= 20 :
        return 1.0
    else :
        return wash_time / 20

def process_alcohol_percentage_point(alcohol_percentage):
    alcohol_percentage = int(alcohol_percentage)
    if alcohol_percentage < 60 :
        return 0.0
    elif alcohol_percentage < 80 :
        return (alcohol_percentage - 60) / 20
    else :
        return 1.0

def process_mask_behavior_point(behavior_list):
    behavior_point = 1.0
    for behavior in behavior_list :
        for mask_behavior_point in MASK_BEHAVIOR_POINT:
            if behavior == mask_behavior_point[1]:
                behavior_point += float(mask_behavior_point[0])

    behavior_point = round(behavior_point, 2)

    if behavior_point < 0.0 :
        return 0.0
    else :
        return behavior_point

def proccess_sanitize_wash_time(sanitize_wash_time):
    if sanitize_wash_time != 1 :
        unit_time = ' seconds'
    else :
        unit_time = ' second'
    return str(sanitize_wash_time) + unit_time

def process_sanitize_occasions_point(occasions_list):
    occasions_point = 0.0
    for occasions in occasions_list :
        for sanitize_occasions_point in SANITIZE_OCCASIONS_POINT :
            if occasions == sanitize_occasions_point[1]:
                occasions_point += float(sanitize_occasions_point[0])
    return occasions_point

def process_mask_percentage(mask_type, behavior_list):
    type_point = 0.0
    behavior_point = 0.0

    for mask_mask_point in MASK_TYPE_POINT:
        if mask_type == mask_mask_point[1]: #iterate to get the point
            type_point = float(mask_mask_point[0])

    behavior_point = process_mask_behavior_point(behavior_list)
    float_percentage = (type_point + behavior_point) / 2 * 100
    return floor(float_percentage)

def process_pd_percentage(exp, crowdedness, openness):
    exp_point = 0.0
    crowdedness_point = 0.0
    openness_point = 0.0

    for pd_exp_point in PD_EXP_POINT:
        if exp == pd_exp_point[1]:
            exp_point = float(pd_exp_point[0])

    for pd_crowdedness_point in PD_CROWDED_AREA_POINT:
        if crowdedness == pd_crowdedness_point[1]:
            crowdedness_point = float(pd_crowdedness_point[0])

    for pd_openness_point in PD_OPEN_AREA_POINT:
        if openness == pd_openness_point[1]:
            openness_point = pd_openness_point[0]

    float_percentage = (exp_point + crowdedness_point + openness_point) / 2 * 100
    return floor(float_percentage)

def process_sanitize_percentage(wash_hand, soap_type, wash_time, 
    hsanitizer, occasions_list, alcohol_percentage, disinfect) :

    wash_hand_point = 0.0
    soap_type_point = 0.0
    hsanitizer_point = 0.0
    disinfect_point = 0.0

    wash_time_point = process_wash_time_point(wash_time)
    occasions_point = process_sanitize_occasions_point(occasions_list)
    alcohol_percentage_point = process_alcohol_percentage_point(alcohol_percentage)

    for sanitize_wash_hand_point in SANITIZE_YES_NO_WASH_HAND_POINT:
        if wash_hand == sanitize_wash_hand_point[1]:
            wash_hand_point = sanitize_wash_hand_point[0]
    
    for sanitize_soap_type_point in SANITIZE_SOAP_TYPE_POINT:
        if soap_type == sanitize_soap_type_point[1]:
            soap_type_point = sanitize_soap_type_point[0]
    
    for sanitize_hsanitizer_point in SANITIZE_YES_NO_H_SANITIZER_POINT:
        if hsanitizer == sanitize_hsanitizer_point[1]:
            hsanitizer_point = sanitize_hsanitizer_point[0]
    
    for sanitize_disinfect_point in SANITIZE_YES_NO_DISINFECT_POINT:

simulation/templates/simul-index.html
{% load static %}

{% include 'header.html' %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/simulation.css' %}">
{% endblock %}

{% block title %}
<title>Simulation</title>
{% endblock title %}

<body>
    {% include 'navbar.html' %}
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    {% block content %}

    <div class="container base-container">            
        <h2 class="feature-tagline" style="text-align: center;">ACTIVE CASE SIMULATOR</h2>
            <div class="forms-card" id="forms-card-simulation-container">
                <h3 class="forms-question" style="text-align: center;">Simulate expected daily test count to get predicted new daily active cases.</h3><br>
                <div id="forms-card-simulation">
                    <input type="number" class="forms-survey-typing-field" id="simulate-test" placeholder="Insert test count..." name="keyword">
                    <div id="test-result">

                    </div>
                </div>
            </div> 
            
            <hr style="border-width: 0.2rem;"/>

        <h2 class="feature-tagline" style="text-align: center; margin-top: 2rem;">PROTOCOL OBEDIENCE SURVEY</h2>
        <div class="card-text" style="text-align: center;">
            Out of people who have taken the survey, ...
            <!-- Summing up your protocol obedience regarding COVID-19 pandemic -->
        </div>
        <div class="container">
            <div class="row percentage-list">
                <div class="col percentage-item">
                    <div class="card-body">
                        <p class="percentage-number">{{ mask_percentage }}<span class="percentage-sign">%</span></p>
                        <p class="percentage-detail">Wear Masks Properly <br> in Public Places</p>
                    </div>
                </div>

                <div class="col percentage-item">
                    <div class="card-body">
                        <p class="percentage-number">{{ pd_percentage }}<span class="percentage-sign">%</span></p>
                        <p class="percentage-detail">Aware of and Practice <br> Physical Distancing</p>
                    </div>
                </div>

                <div class="col percentage-item">
                    <div class="card-body">
                        <p class="percentage-number">{{ sanitize_percentage }}<span class="percentage-sign">%</span></p>
                        <p class="percentage-detail">Wash or Sanitize Hands <br> and Disinfect Regularly</p>
                    </div>
                </div>
            </div>

            {% if not user.is_authenticated %}
            <h4> (You need to login before taking the survey) </h4> <br>
            <a href="{% url 'simulation:simulation-survey' %}" >
                <button type="button" class="back-button" method="GET" id="take-survey-button">Login and Take Survey</button>
            </a>

            {% else %}
            <a href="{% url 'simulation:simulation-survey' %}" >
                <button type="button" class="back-button" method="GET" id="take-survey-button">Take Survey</button>
            </a>
            
            {% endif %}

        </div>

        <!-- <div class="forms-card">
            <form action="/simulation/score/" method="POST">
                {% csrf_token %}
                {% for field1 in mask_form %}
                    <label class="forms-question" style="text-align: left;" for="{{ field1.auto_id }}">{{ field1.label }}</label>
                    {{ field1 }}
                {% endfor %}
        
                {% for field2 in pd_form %}
                    <label class="forms-question" style="text-align: left;" for="{{ field2.auto_id }}">{{ field2.label }}</label>
                    {{ field2 }}
                {% endfor %}
        
                {% for field3 in sanitize_form %}
                    <label class="forms-question" style="text-align: left;" for="{{ field3.auto_id }}">{{ field3.label }}</label>
                    {{ field3 }}
                {% endfor %}
                
                <div class="forms-card" id="forms-card-survey-button">
                    <div id="forms-card-survey-button">
                        <button type="submit" name="survey_submission" class="survey-button">Submit</button>
                    </div>
                </div>
            </form>
        </div> -->


    </div>

    <script src="{% static 'js/simul-index.js' %}"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
    integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
    crossorigin="anonymous"></script>
    {% endblock content %}
    {% include 'footer.html' %}
</body>

simulation/templates/simul-result.html
{% load static %}

{% include 'header.html' %}
{% include 'navbar.html' %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/simulation.css' %}">
{% endblock %}

{% block title %}
<title>Simulation - Result</title>
{% endblock title %}

<body>
    
    <div class="container base-container">
        <div class="container feature-container" style="margin-top: 3rem;">
            <h2 class="feature-tagline" style="text-align: center;">SIMULATION RESULT</h2>
            <h3 class="forms-card" style="text-align: center; margin-top: 5rem; padding: 2rem;">
                Out of <span style="background-color: white;">{{ test_count }}</span> taken tests, 
                there would be: <br> <br>
                <span style="font-size: 4rem;">{{ new_case }}</span>
                <br> <br>
                New Cases <br><br>

                <a href="{{ request.META.HTTP_REFERER }}" >
                    <button type="button" class="back-button" method="GET">&lt&lt&lt back</button>
                </a>
            </h3>

        </div>
    </div>
    {% include 'script.html' %}
    {% include 'footer.html' %}
</body>

simulation/templates/simul-score.html
{% load static %}

{% include 'header.html' %}
{% include 'navbar.html' %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/simulation.css' %}">
{% endblock %}

{% block title %}
<title>Simulation - Survey Score</title>
{% endblock title %}

<body>
    
    <div class="container base-container">
        <div class="container feature-container" style="margin-top: 3rem;">
            <h2 class="feature-tagline" style="text-align: center;">SURVEY SUMMARY</h2>
            <div class="forms-card" style="text-align: center; margin-top: 5rem; padding: 2rem;">
                <h3>Thank you for filling out our survey!</h3><br>
                <h4>According to your recently taken survey, you scored:</h4> <br>

                <div class="container">
                    <div class="row percentage-list" style="margin-top: 0rem;">
                        <div class="col percentage-item">
                            <div class="card-body">
                                <p class="percentage-number">{{ mask_percentage }}<span class="percentage-sign">/100</span></p>
                                <p class="percentage-detail">of Wearing<br>Masks Properly <br> in Public Places</p>
                            </div>
                        </div>
    
                        <div class="col percentage-item">
                            <div class="card-body">
                                <p class="percentage-number">{{ pd_percentage }}<span class="percentage-sign">/100</span></p>
                                <p class="percentage-detail">of Being Aware of<br>and Practicing<br>Physical Distancing</p>
                            </div>
                        </div>
    
                        <div class="col percentage-item">
                            <div class="card-body">
                                <p class="percentage-number">{{ sanitize_percentage }}<span class="percentage-sign">/100</span></p>
                                <p class="percentage-detail">of Washing or<br> Sanitizing Hands and<br>Disinfecting Regularly</p>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- START KODINGAN DEMO -->
                <h3>Your Response:</h3><br>

                {% for question, answer in mask_response %}
                    <div class="forms-question answer" style="text-align: left;">{{ question }}</div>
                    <div class="forms-answer" style="text-align: left; margin: 0.5em 0 1.5em 2em;">{{ answer|linebreaksbr }}</div>
                {% endfor %}

                {% for question, answer in pd_response %}
                    <div class="forms-question answer" style="text-align: left;">{{ question }}</div>
                    <div class="forms-answer" style="text-align: left; margin: 0.5em 0 1.5em 2em;">{{ answer }}</div>
                {% endfor %}

                {% for question, answer in sanitize_response %}
                    <div class="forms-question answer" style="text-align: left;">{{ question }}</div>
                    <div class="forms-answer" style="text-align: left; margin: 0.5em 0 1.5em 2em;">{{ answer|linebreaksbr }}</div>
                {% endfor %}
                
                <!-- END KODINGAN DEMO -->


                <h3 style="margin-top: 3rem;">Keep your protocol obedience spirit up! :D</h3>
                <br> <br>
                <a href="{% url 'simulation:simulation' %}" >
                    <button type="button" class="back-button" method="GET">&lt&lt&lt back</button>
                </a>

            </div>
        </div>
    </div>
    {% include 'script.html' %}
    {% include 'footer.html' %}
</body>

simulation/templates/simul-survey.html
{% load static %}

{% include 'header.html' %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/simulation.css' %}">
{% endblock %}

{% block title %}
<title>Simulation - Survey</title>
{% endblock title %}

<body>
    {% include 'navbar.html' %}
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"> -->
    <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script> -->
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    {% block content %}

    <div class="container base-container">  

        <h2 class="feature-tagline" style="text-align: center; margin-top: 2rem;">PROTOCOL OBEDIENCE SURVEY</h2>
        <div class="card-text" style="text-align: center;">
            Out of people who have taken the survey, ...
            <!-- Summing up your protocol obedience regarding COVID-19 pandemic -->
        </div>
        <div class="container">
            <div class="row percentage-list">
                <div class="col percentage-item">
                    <div class="card-body">
                        <p class="percentage-number" id="mask-percentage"><span class="percentage-sign">%</span></p>
                        <p class="percentage-detail">Wear Masks Properly <br> in Public Places</p>
                    </div>
                </div>

                <div class="col percentage-item">
                    <div class="card-body">
                        <p class="percentage-number" id="pd-percentage"><span class="percentage-sign">%</span></p>
                        <p class="percentage-detail">Aware of and Practice <br> Physical Distancing</p>
                    </div>
                </div>

                <div class="col percentage-item">
                    <div class="card-body">
                        <p class="percentage-number" id="sntz-percentage"><span class="percentage-sign">%</span></p>
                        <p class="percentage-detail">Wash or Sanitize Hands <br> and Disinfect Regularly</p>
                    </div>
                </div>
            </div>
        </div>

        <button type="button" id="show-hide-survey-button" class="survey-button" value="Shown">Hide Survey</button>

        <div class="forms-card" style="margin-top: 3rem;" id="main-survey">
            <form action="/simulation/score/" method="POST">
                {% csrf_token %}
                {% for field1 in mask_form %}
                    <label class="forms-question" style="text-align: left;" for="{{ field1.auto_id }}">{{ field1.label }}</label>
                    {{ field1 }}
                {% endfor %}
        
                {% for field2 in pd_form %}
                    <label class="forms-question" style="text-align: left;" for="{{ field2.auto_id }}">{{ field2.label }}</label>
                    {{ field2 }}
                {% endfor %}
        
                {% for field3 in sanitize_form %}
                    <label class="forms-question" style="text-align: left;" for="{{ field3.auto_id }}">{{ field3.label }}</label>
                    {{ field3 }}
                {% endfor %}
                
                <div class="forms-card" id="forms-card-survey-button">
                    <div id="forms-card-survey-button">
                        <button type="submit" name="survey_submission" class="survey-button" id="survey-submit-button">Submit</button>
                    </div>
                </div>
            </form>
        </div>

        <h3 class="feature-tagline" style="text-align: center; margin-top: 5rem;">SURVEY RESPONSES</h3>


        <div class="response-container">

        </div>

        <br> <br>
        <a href="{% url 'simulation:simulation' %}" >
            <button type="button" class="back-button" method="GET">&lt&lt&lt back</button>
        </a>
        <br> <br>

    </div>

    <script src="{% static 'js/simul-survey.js' %}"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
    integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
    crossorigin="anonymous"></script>
    {% endblock content %}
    {% include 'footer.html' %}
</body>