fitur/urls.py
from django.urls import path
from . import views
app_name = 'fitur'

urlpatterns = [
    path('tipsform/', views.tipsform, name= 'tips_form'),
    path('guide', views.guide, name='guide'),
    path('', views.tipslist, name= 'tips_list'),
    

]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
   
]

teka/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('otentikasi.urls')),
    path('simulation/', include('simulation.urls')),
    path('tips/', include('fitur.urls')),
    path('maps/', include('maps.urls')),
    path('feedback/', include('feedback.urls')),
]

fitur/models.py
from django.db import models

# Create your models here.
class Fiturku(models.Model):
    tips = models.CharField(max_length = 500, null=True)
    description = models.TextField(max_length=1000, null=True)

    def __str__(self):
        return self.tips

fitur/forms.py
from django import forms
from .models import Fiturku

class Fiturform(forms.ModelForm):

    class Meta :
        model = Fiturku
        fields = '__all__'
        
        tips = forms.CharField(label="Tips", widget=forms.TextInput(attrs={
            "id" : "tips",
            "class" : "form-control mb-3",
           
        }))

        description = forms.CharField(label="Description", widget=forms.TextInput(attrs={
            "id" : "description",
            "class" : "form-control mb-3",
            
        }))
        
       

fitur/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,JsonResponse
from django.core import serializers
from .forms import Fiturform
from .models import Fiturku


def tipslist(request):
    form = Fiturform()
    listp = Fiturku.objects.all()
    if request.is_ajax and request.method == 'POST':
        print(request)
        form = Fiturform(request.POST)
        if form.is_valid():
            data = form.save()
            json_tips = serializers.serialize('json', [data, ])
            return JsonResponse({"tips":json_tips},status=200)
        else:
            return JsonResponse({"error": form.errors}, status=400)

    context = {
        "namanya" : request.user.username,
        "listp" : listp,
        "form" : form,
    }
    return render (request, 'fitur/tips_list.html', context)

#@login_required(login_url="login")
def tipsform(request):
    form = Fiturform()
    if request.method == 'POST':
        form = Fiturform(request.POST)
        print(form)
        if form.is_valid():
            data = form.save()
            return JsonResponse(data)

    #return render (request, 'fitur/tips_form.html', {'form':form})

def guide(request):
    return render (request, "fitur/tips_guide.html")

fitur/templates/fitur/tips_form.html
{% load static %}
{% load crispy_forms_tags %}
{% include 'header.html' %}
{% block css %}
<link rel="stylesheet" href="{% static 'fitur/tips.css' %}">
{% endblock %}

{% block title %}
<title>Tips - NCovid</title>
{% endblock title %}

<body>
    {% include 'navbar.html' %}
    {% block content %}
    
    <div class="home-container">
      <h2 id= "feature-tagline" style="text-align: center;">TIPS TO PROTECT YOURSELF FROM CORONAVIRUS</h2>
        <!-- <div class="row justify-content-center">
          <div class="col-8"> -->
            <h2>Enter Your Tips Advice Here</h2>
            <hr class="mt-0 mb-4">
            <form method="POST">
              {% csrf_token %}
              {{ form|crispy }}
              <br>
              <br>
              <button type="submit" class="btn btn-primary">Submit</button>
              <a type="button" class="btn btn-light" href="{% url 'fitur:tips_list' %}"><b>Back</b></a>
            </form>
          
            <br>
   

    

  </div>
    <br>
    <br>
    {% include 'script.html' %}
    {% endblock content %}
    {% include 'footer.html' %}
</body>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="{% static 'javascript/js/script.js' %}"></script>
   

fitur/templates/fitur/tips_guide.html
{% load static %}

{% include 'header.html' %}
{% block css %}
<link rel="stylesheet" href="{% static 'fitur/tips.css' %}">
{% endblock %}

{% block title %}
<title>Tips - NCovid</title>
{% endblock title %}

<head>
    <!-- Bootstrap CSS -->
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>

<body>
    {% include 'navbar.html' %}
    {% block content %}

            <div class="home-container">
                <h2 id= "feature-tagline" style="text-align: center;">GUIDELINE TO SHARE YOUR TIPS</h2>
                    <br>
                    <br>
                    <div id="accordion">
                      <!-- <div class="row justify-content-center">
                          <div class="col-8"> -->
                          <h3 position="0" class="p-2 m-0 accordion-tab text-light bg-dark">
                              Purpose
                              <span class="mx-1 float-right down" id="down">
                                  ↓
                              </span>
                              <span class="mx-1 float-right up" id="up">
                                  ↑
                              </span>
                          </h3>
                          <p position="0" class="p-1 m-0 bg-success text-light bg-info">
                            This form aims to contain tips on maintaining your health<br>
                            One tip from you is very useful for all visitors to our website<br>
                          </p>
                          <h3 position="1" class="p-2 m-0 accordion-tab text-light bg-dark">
                            Hint
                            <span class="mx-1 float-right down" id="down">
                                ↓
                            </span>
                            <span class="mx-1 float-right up" id="up">
                                ↑
                            </span>
                          </h3>
                          <p position="1" class="p-1 m-0 bg-success text-light bg-info">
                              You can fill out this health tips form by entering the title of the tips <br>
                              Then you have to fill in the details of the tips that you enter in the description section<br>
                              Tips yang anda masukkan maksimal 500 kata<br>
                              Description masing-masing tips maksimal 1000 kata<br>
                          </p>
                          <h3 position="2" class="p-2 m-0 accordion-tab text-light bg-dark">
                            Provisions
                            <span class="mx-1 float-right down" id="down">
                                ↓
                            </span>
                            <span class="mx-1 float-right up" id="up">
                                ↑
                            </span>
                          </h3>
                          <p position="2" class="p-1 m-0 bg-success text-light bg-info">
                            Tips that you enter contains maximum of 500 words<br>
                            Description of each tip contains maximum of 1000 words<br>
                          </p>
                    </div>
                    <br>
                    <br>
                    <a type="button" class="btn btn-light" href="{% url 'fitur:tips_list' %}"><b>Back</b></a>
            </div>
            <br>
            <br>


    {% endblock content %}
    {% include 'footer.html' %}
</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="{% static 'javascript/js/acordion.js' %}"></script>

fitur/templates/fitur/tips_list.html
{% load static %}
{% load crispy_forms_tags %}
{% include 'header.html' %}
{% block css %}
<link rel="stylesheet" href="{% static 'fitur/tips.css' %}">

{% endblock css %}

{% block title %}
<title>Tips - NCovid</title>
{% endblock title %}


<body>
    {% include 'navbar.html' %}
    {% block content %}
    
   
    <div class="home-container">
      <h2 id= "feature-tagline" style="text-align: center;">TIPS TO PROTECT YOURSELF FROM CORONAVIRUS</h2>
      <h3 id= "feature-tagline" style="text-align: center;">Welcome {{ namanya }} ! here some tips advice for you</h3>
        <div class="row justify-content-center">
          <div class="col-8">
                <div id='tipslist'>
                {% for i in listp %}
                <div class="card" style="border-radius: 20px;">
                  <div class="card-header">
                  <b>{{ i.tips }}</b>
                  </div>
                
                  <div class="card-body" style="margin: auto;">
                      <div class="card-text" style="margin: auto; text-align: center;"><b>{{ i.description }}</b></div>

                  </div>
                </div>
                {% endfor %}
              </div>
            <br>
            {% if request.user.is_authenticated %}
           
            <div class="home-container">
              <h2 id= "feature-tagline" style="text-align: center;">TIPS TO PROTECT YOURSELF FROM CORONAVIRUS</h2>
                <!-- <div class="row justify-content-center">
                  <div class="col-8"> -->
                    <h2>Enter Your Tips Advice Here</h2>
                    <hr class="mt-0 mb-4">
                    <form id="form" method="POST">
                      {% csrf_token %}
                      {{ form|crispy }}
                      <br>
                      <br>
                      <button type="submit" class="btn btn-primary">Submit</button>
                      <a type="button" class="btn btn-light" href="{% url 'fitur:tips_list' %}"><b>Back</b></a>
                      <a type="button" class="btn btn-dark" href="{% url 'fitur:guide' %}"><b>Read Guideline</b></a>
                    </form>
                    <br>
                    <br>
                    <br>
            
            {% else %}
            <a class="btn btn-dark" style="margin-bottom: 40px;" href="{% url 'login' %}"><b>Add Tips</b></a>
            {% endif %}
        </div>
      </div>
    </div>

    

    
    {% endblock content %}
    {% include 'footer.html' %}
</body>

<script
  src="https://code.jquery.com/jquery-3.5.1.js"
  integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
  crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
    integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
    crossorigin="anonymous"></script>
<script src="{% static 'javascript/js/script.js' %}"></script>