home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
   
]

maps/urls.py
from django.urls import path

from . import views

app_name = 'maps'

urlpatterns = [
    path('', views.maps, name='maps'),
    path('report/', views.report, name='report'),
    path('self-reports/', views.reports, name='self-reports'),
    path('get-data/<int:num_data>/<int:num_get>/', views.get_data, name='get-data'),
]

teka/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('otentikasi.urls')),
    path('simulation/', include('simulation.urls')),
    path('tips/', include('fitur.urls')),
    path('maps/', include('maps.urls')),
    path('feedback/', include('feedback.urls')),
]

maps/models.py
from django.db import models
from django.utils import timezone
import pytz


class Report(models.Model):
    age = models.IntegerField()
    gender = models.CharField(max_length=10)
    status = models.CharField(max_length=20, null=True)
    province = models.CharField(max_length=30, null=True)
    city = models.CharField(max_length=30)
    dt = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        timezone.activate(pytz.timezone("Asia/Jakarta"))
        cur = timezone.get_current_timezone()
        self.dt = cur.normalize(self.dt)
        return self.dt.strftime('%b %d, %Y @ %H:%M')

maps/forms.py
from django import forms
from . import models

class ReportForm(forms.ModelForm):
    class Meta:
        model = models.Report
        fields = '__all__'

    age = forms.IntegerField(label='Age', max_value=120, min_value=1, widget=forms.TextInput(attrs=
    {
        'required' : 'True',
        'placeholder' : 'Age'
    }))

    gender = forms.CharField(label='Gender', widget=forms.Select(attrs=
    {
        'required' : 'True',
    }, choices=(
        ('M', 'Male'),
        ('F', 'Female')
    )))

    status = forms.CharField(label='Status', widget=forms.Select(attrs=
    {
        'required' : 'True',
    }, choices=(
        (None, '---Pick Status---'),
        ('Positive', 'Positive'),
        ('Symptomatic', 'Showing Symptoms'),
        ('Recovered', 'Recovered')
    )))

    province = forms.CharField(label='Province', widget=forms.Select(attrs=
    {
        'required' : 'True',
    }, choices=(
        (None, '---Pick Province---'),
        ('Aceh', 'Aceh'),
        ('Sumatera Utara', 'Sumatera Utara'),
        ('Sumatera Barat', 'Sumatera Barat'),
        ('Riau', 'Riau'),
        ('Jambi', 'Jambi'),
        ('Sumatera Selatan', 'Sumatera Selatan'),
        ('Bengkulu', 'Bengkulu'),
        ('Lampung', 'Lampung'),
        ('Kep. Bangka Belitung', 'Kepulauan Bangka Belitung'),
        ('Kep. Riau', 'Kepulauan Riau'),
        ('DKI Jakarta', 'DKI Jakarta'),
        ('Jawa Barat', 'Jawa Barat'),
        ('Jawa Tengah', 'Jawa Tengah'),
        ('DI Yogyakarta', 'DI Yogyakarta'),
        ('Jawa Timur', 'Jawa Timur'),
        ('Banten', 'Banten'),
        ('Bali', 'Bali'),
        ('Nusa Tenggara Barat', 'Nusa Tenggara Barat'),
        ('Nusa Tenggara Timur', 'Nusa Tenggara Timur'),
        ('Kalimantan Barat', 'Kalimantan Barat'),
        ('Kalimantan Tengah', 'Kalimantan Tengah'),
        ('Kalimantan Selatan', 'Kalimantan Selatan'),
        ('Kalimantan Timur', 'Kalimantan Timur'),
        ('Kalimantan Utara', 'Kalimantan Utara'),
        ('Sulawesi Utara', 'Sulawesi Utara'),
        ('Sulawesi Tengah', 'Sulawesi Tengah'),
        ('Sulawesi Selatan', 'Sulawesi Selatan'),
        ('Sulawesi Tenggara', 'Sulawesi Tenggara'),
        ('Gorontalo', 'Gorontalo'),
        ('Sulawesi Barat', 'Sulawesi Barat'),
        ('Maluku', 'Maluku'),
        ('Maluku Utara', 'Maluku Utara'),
        ('Papua Barat', 'Papua Barat'),
        ('Papua', 'Papua')
    )))

    city = forms.CharField(label='City', widget=forms.TextInput(attrs=
    {
        'required' : 'True',
        'placeholder' : 'City'
    }))

maps/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from maps.forms import ReportForm
from maps.models import Report

def maps(request):
    data = Report.objects.all().order_by('id').reverse()[:10]
    context = {
        'data' : data,
    }
    return render(request, 'maps.html', context)

@login_required(login_url='/login/')
def report(request):
    if request.user.is_authenticated:
        form = ReportForm(request.POST or None)
        if form.is_valid and request.method == 'POST':
            Report.objects.create(age=request.POST['age'], gender=request.POST['gender'], status=request.POST['status'], province=request.POST['province'], city=request.POST['city'])
            return JsonResponse({'data' : 'success'})
        context = {
            'form' : form,
        }
        return render(request, 'report.html', context)

def reports(request):
    data = Report.objects.all()
    context = {
        'data' : data,
    }
    return render(request, 'reports.html', context)

def get_data(request, num_data, num_get):
    upper = num_data
    lower = upper - num_get
    data = list(Report.objects.values())
    data.sort(key=lambda k: k['id'], reverse=True)
    data = data[lower:upper]
    for i in data:
        i['dt'] = str(Report.objects.get(id=i['id']))
    limit = True if upper >= len(Report.objects.all()) else False
    return JsonResponse({'data' : data, 'limit' : limit})

maps/templates/maps.html
{% load static %}

{% include 'header.html' %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/maps.css' %}">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
{% endblock %}

{% block title %}
<title>Maps - NCovid</title>
{% endblock title %}

<body>
    {% include 'navbar.html' %}
    {% block content %}
    <div class="container home-container">
        <h2 id="feature-tagline">COVID DISTRIBUTION MAP IN INDONESIA</h2>
        <div class="map">
            <script src="//my.visme.co/visme-embed.js"></script>
            <div class="visme_d" data-url="dmdoegov-ncovid" data-w="1920" data-h="1080" data-domain="my"></div>
        </div>
        <br><br><br>
        <h2 class="text-left">SELF REPORTS<div class="btn">
            <a href="/maps/report/"><i class="material-icons add">add_box</i></a>
        </div><a href="/maps/self-reports/" class="float-right showAll">Show all</a></h2>
        {% if data.first != None %}
        <table class="table table-striped table-light table-responsive-lg mb-4" id="reports">
            <thead style="background-color: #1FAD95; color: white;">
                <th scope="col">No</th>
                <th scope="col">Age</th>
                <th scope="col">Gender</th>
                <th scope="col">Status</th>
                <th scope="col">Province</th>
                <th scope="col">City</th>
                <th scope="col">Date Added</th>
            </thead>
        </table>
        <a class="showMore" id="load-btn">Show more</a>
        {% else %}
        <div class="col-8 text-black text-left pl-0">
          <h4>There are no data yet...😷</h4>
        </div>
        {% endif %}
        <br><br>
    </div>
    {% include 'script.html' %}
    <script>
        $(document).ready(function(){

            const reports = $('#reports');
            const loadBtn = $('#load-btn');
            let visible = 10;
            let count = 1;

            function getData(){
                $.ajax({
                type: 'GET',
                url: `/maps/get-data/${visible}/10/`,

                success: function(response){
                    // console.log(response.data)
                    $.each(response.data, function(i, item) {
                        if (item.gender == 'F') {
                            var icon = `<img src="{% static 'images/female.png' %}" class="g-icon">`
                        } else {
                            var icon = `<img src="{% static 'images/male.png' %}" class="g-icon">`
                        }

                        if (item.status == 'Positive') {
                            var color = `#dc3545;`
                        } else if (item.status == 'Recovered') {
                            var color = `#28a745;`
                        } else {
                            var color = `#ffc107;`
                        }
                        reports.append(
                            `<tr>
                                <td class="align-middle">${count}</td>
                                <td class="align-middle">${item.age}</td>
                                <td class="align-middle">${icon}</td>
                                <td class="align-middle">
                                    <span class="status" style="color: white; background-color: ${color}">
                                        ${item.status}
                                    </span>
                                </td>
                                <td class="align-middle">${item.province}</td>
                                <td class="align-middle">${item.city}</td>
                                <td class="date align-middle">${item.dt} WIB</td>
                            </tr>`
                        )
                        count++;
                    })
                    if (response.limit) {
                        loadBtn.text('No more data to show');
                        loadBtn.addClass('disabled');
                    }
                }
            })}

            getData();

            loadBtn.click(function(){
                visible += 10;
                getData();
            })
        })

    </script>
    {% endblock content %}
    {% include 'footer.html' %}
</body>

maps/templates/report.html
{% load static %}
{% load crispy_forms_tags %}

{% include 'header.html' %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/maps.css' %}">
{% endblock %}

{% block title %}
<title>Self Report - NCovid</title>
{% endblock title %}

<body>
    {% include 'navbar.html' %}
    {% block content %}
    <div class="container home-container">
        <h2 id="feature-tagline">SELF REPORT</h2>
        <form method="POST" id="formReport">
            {% csrf_token %}
            <div class="form-row text-left mx-4">
                <div class="form-group col-md-6">
                    <div class="form-row">
                        <div class="col-md-4">{{ form.age|as_crispy_field }}</div>
                        <div class="col-md-8">{{ form.gender|as_crispy_field }}</div>
                    </div>
                    {{ form.status|as_crispy_field }}
                </div>
                <div class="form-group col-md-6">
                    {{ form.province|as_crispy_field }}
                    {{ form.city|as_crispy_field }}
                </div>
                <div class="form-group float-right w-100">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a href="/maps" class="btn btn-danger">Cancel</a>
                    <div id="ajax">
                        <a href="/maps/self-reports/">View All Reports</a>
                    </div>
                </div>
            </div>
        </form>
        <br>
    </div>
    {% include 'script.html' %}
    <script>
        $(document).on('submit', '#formReport', function(e) {
            e.preventDefault();
            const formReport = $('#formReport');
            const ajaxDiv = $('#ajax');

            $.ajax({
                type : 'POST',
                url : '/maps/report/',
                data : {
                    age : $('#id_age').val(),
                    gender : $('#id_gender').val(),
                    status : $('#id_status').val(),
                    province : $('#id_province').val(),
                    city : $('#id_city').val(),
                    csrfmiddlewaretoken : $('input[name=csrfmiddlewaretoken').val(),
                },
                success: function(response){
                    // console.log(response.data);
                    if (response.data == 'success') {
                        formReport.trigger('reset');
                        if (ajaxDiv.css('display') == 'none') {
                            ajaxDiv.css('display', 'inline-flex');
                        }
                    }
                } 
            })
        })
    </script>
    {% endblock content %}
    {% include 'footer.html' %}
</body>

maps/templates/reports.html
{% load static %}
{% load crispy_forms_tags %}

{% include 'header.html' %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/maps.css' %}">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
{% endblock %}

{% block title %}
<title>Reports - NCovid</title>
{% endblock title %}

<body>
    {% include 'navbar.html' %}
    {% block content %}
    <div class="container home-container">
        <h2 id="feature-tagline">REPORTS<div class="btn">
            <a href="/maps/report/"><i class="material-icons add">add_box</i></a>
        </div></h2>
        {% if data.first != None %}
        <table class="table table-striped table-light table-responsive-lg mb-4" id="reports">
            <thead style="background-color: #1FAD95; color: white;">
                <th scope="col">No</th>
                <th scope="col">Age</th>
                <th scope="col">Gender</th>
                <th scope="col">Status</th>
                <th scope="col">Province</th>
                <th scope="col">City</th>
                <th scope="col">Date Added</th>
            </thead>
        </table>
        <a class="showMore" id="load-btn">Show more</a>
        {% else %}
        <div class="col-8 text-black mx-auto">
          <h4>There are no data yet...😷</h4>
        </div>
        {% endif %}
        <br><br>
    </div>
    {% include 'script.html' %}
    <script>
        $(document).ready(function(){

            const reports = $('#reports');
            const loadBtn = $('#load-btn');
            let visible = 20;
            let count = 1;

            function getData(){
                $.ajax({
                type: 'GET',
                url: `/maps/get-data/${visible}/20/`,

                success: function(response){
                    // console.log(response.data)
                    $.each(response.data, function(i, item) {
                        if (item.gender == 'F') {
                            var icon = `<img src="{% static 'images/female.png' %}" class="g-icon">`
                        } else {
                            var icon = `<img src="{% static 'images/male.png' %}" class="g-icon">`
                        }

                        if (item.status == 'Positive') {
                            var color = `#dc3545;`
                        } else if (item.status == 'Recovered') {
                            var color = `#28a745;`
                        } else {
                            var color = `#ffc107;`
                        }
                        reports.append(
                            `<tr>
                                <td class="align-middle">${count}</td>
                                <td class="align-middle">${item.age}</td>
                                <td class="align-middle">${icon}</td>
                                <td class="align-middle">
                                    <span class="status" style="color: white; background-color: ${color}">
                                        ${item.status}
                                    </span>
                                </td>
                                <td class="align-middle">${item.province}</td>
                                <td class="align-middle">${item.city}</td>
                                <td class="date align-middle">${item.dt} WIB</td>
                            </tr>`
                        )
                        count++;
                    })
                    if (response.limit) {
                        loadBtn.text('No more data to show');
                        loadBtn.addClass('disabled');
                    }
                }
            })}

            getData();

            loadBtn.click(function(){
                visible += 20;
                getData();
            })
        })

    </script>
    {% endblock content %}
    {% include 'footer.html' %}
</body>